services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: kingofthecord-mongodb
    restart: unless-stopped
    ports:
      - '${MONGODB_PORT:-27017}:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DB:-kingofthecord}

volumes:
  mongodb_data:
